Add functionality for dataframes
yieldbot/flambo pull request #126
Opened 2017-11-16 03:36 UTC by plandes

Since data frames are the next big thing in Spark, I have added functions to do things like this:

```clojure
(-> (...create sql session...)
    (df/map row-encoder (f/fn ...
```

Note that unlike RDDs you have to specify the encoder.  I can add more documentation if you like.

Also I have a lot of other things I could add for using flambo with spark.  Also I have gotten a repl to work in Spark ([powderkeg](https://github.com/cgore/powderkeg) not necessary).  However, I wanted things slowly this seems like an inactive project.

Love Flambo--its been very helpful in my research so kudos for making a great software package!

Regards,
Paul

2017-11-16 14:00 UTC, NonaryR commented
Hi @plandes, great work! 
Can you provide some example or test of this functionality?
For example, simple mapping and filtering over dataframe?

2017-11-20 16:04 UTC, NonaryR commented
@plandes any updates?

2017-11-22 12:55 UTC, plandes commented
Sorry, not yet.  This week is tough, but I'll have time to address this over the weekend.  It's not trivial to provide an example by copy/paste since I've written a lot of helper libraries around flambo.  I could contribute those as well (as mentioned) but then the pull request wouldn't be trivial.

2017-11-25 22:07 UTC, plandes commented
I've come up with something that should make sense--although there is a missing function.  Again it should make sense.

Note that this is a contrived example because I have many other functions I now use to do things like create cached (think mutex protected atom) Spark context, session, RowEncoder (needed for data frames) and many other functions needed for the new DataFrame API.

Again, let me know if you have questions, but maybe a larger pull request would be easier.  Up to you.

```clojure
(let [struct (->> ["id" "host" "yada"]
                    (map #(hash-map :name %))
                    (#(concat % [{:name "some_score" :type :integer}]))
                    sql/struct-type)
        row-encoder (RowEncoder/apply struct)
        query (str "select id, some_text from some_table"
                   (if limit (format " limit %d" limit)))]
  (-> (conf/spark-conf)
      (conf/app-name "name")
      (f/spark-cluster)
      (.getOrCreate (SparkSession/builder))
      (.sql query)
      .write
      (.parquet "hdfs://some/tmp/dir")))
```

2017-11-27 22:59 UTC, leon-barrett requested changes
Thank you for this PR! This code definitely looks like a great addition. But I don't think we need a new namespace; can you please move it to the existing namespace `flambo.sql` instead?

Also, if you have time, refining your example and getting it in the readme would be a nice bonus.

Thanks.

2017-11-27 22:59 UTC, leon-barrett commented on src/clojure/flambo/dataframe.clj
> +  "Create a Spark SQL Dataframe for **type**.  The available options for
correction: "Dataframe" -> "Encoder"?

2017-11-27 22:59 UTC, leon-barrett commented on src/clojure/flambo/dataframe.clj
> +        true type))
Brainstorming... as a convenience, it might be nice to be able to pass the raw Class here (e.g. String).

2017-11-27 22:59 UTC, leon-barrett commented on src/clojure/flambo/dataframe.clj
> +(ns ^{:doc "Functions to map, reduce, filter etc just like we do for RDDs."
There are already some dataframe functions (e.g. `agg`) in `flambo.sql`--I think it would be better to put these functions there.

2017-11-27 22:59 UTC, leon-barrett commented on src/clojure/flambo/function.clj
> +         (if-not ~'this
Do you find value in this additional validation? It looks to me like it just throws an exception--I suspect the current behavior (a stack trace of a NullPointerException) would be nearly as readable, but maybe you have a different experience.

2017-11-29 05:56 UTC, plandes commented on src/clojure/flambo/dataframe.clj
> +(ns ^{:doc "Functions to map, reduce, filter etc just like we do for RDDs."
Sure, if you want.  However, sooner or later you might run into naming issues since it's isomorphic from the two namespaces via RDD to DF.  In this case you don't (yet) have an RDD namespace, but I think you'll want one eventually given the movement away from RDD to DF.  This makes it easier to deprecate the former namespace eventually.  But it's your project and won't be so presumptuous as to tell you to make this change.

2017-11-29 05:58 UTC, plandes commented on src/clojure/flambo/dataframe.clj
> +  "Create a Spark SQL Dataframe for **type**.  The available options for
I don't think so, although I could be missing something.  Dataframes are more RDBMS like creatures in nature and need an encoder on the output side (think data sink).  By default they use Java or Kryo serialization (depending on some implicit or some similar thing I don't fully understand in Scala).  Specifying an encoder explicitly gives you a way to more efficiently *encode* your data on the output side of things.

2017-11-29 06:02 UTC, plandes commented on src/clojure/flambo/function.clj
> +         (if-not ~'this
I added this when I was tracking down a NPE and couldn't find it.  It was useful for that, but that might have been an edge case--although I doubt it.

I wouldn't take an issue with you torching it.

2017-11-29 06:05 UTC, plandes commented
Re the moving `dataframe` to `flambo.sql`, this seems like a bigger decision.  If you decide to include it in `flambo.sql` I would respectfully disagree with that solution, but I don't feel terribly strongly about it and would fold it in.

Thanks again for writing flambo!  I believe I mentioned I was able to get it to work in a REPL.  Being able to prototype in a REPL via Cider in Emacs, then reusing code in a `spark-submit` has been tremendously powerful and useful and I have this project to thank for that!

Cheers!

Regards,
Paul

2017-11-29 18:49 UTC, leon-barrett commented on src/clojure/flambo/dataframe.clj
> +  "Create a Spark SQL Dataframe for **type**.  The available options for
I hear you that they're different--but I think your function `encoder-for-type` returns an `Encoder`, not a `Dataframe`.

2017-11-29 18:56 UTC, leon-barrett commented on src/clojure/flambo/dataframe.clj
> +(ns ^{:doc "Functions to map, reduce, filter etc just like we do for RDDs."
I discussed it with Soren, and he argued that because Dataset is in `org.apache.spark.sql` and in a separate jar `spark-sql`, he'd prefer if the Dataset operations were in `flambo.sql`, so I think we prefer that, and I don't think we expect to deprecate `flambo.api`.

2017-11-29 20:38 UTC, plandes commented on src/clojure/flambo/dataframe.clj
> +(ns ^{:doc "Functions to map, reduce, filter etc just like we do for RDDs."
OK, I've moved them over.

2017-11-29 20:38 UTC, plandes commented on src/clojure/flambo/dataframe.clj
> +  "Create a Spark SQL Dataframe for **type**.  The available options for
Oh I see--you're referring to the documentation.  Yes, that's now been corrected.

2017-11-29 20:41 UTC, plandes commented on src/clojure/flambo/dataframe.clj
> +  "Create a Spark SQL Dataframe for **type**.  The available options for
Agree.  Added.

2017-11-29 20:41 UTC, plandes commented on src/clojure/flambo/dataframe.clj
> +        true type))
Agree. Added.

2017-11-29 21:14 UTC, leon-barrett commented on src/clojure/flambo/function.clj
> +         (if-not ~'this
Ah, I see, because the code is a macro, the stack trace doesn't disambiguate these lines, so it's hard to track any such exceptions down. Sure, I can see the value.

2017-11-29 21:16 UTC, leon-barrett commented
Cool, looks good, thanks.

2017-11-29 21:16 UTC, leon-barrett approved these changes

2017-11-29 21:16 UTC, merged