Adding Spark SQL utility functionality
yieldbot/flambo pull request #129
Opened 2017-12-04 03:17 UTC by plandes

This adds several utility functions (i.e. row->map, creating rows, creating views, spark SQL queries).

2017-12-12 06:06 UTC, leon-barrett requested changes
Thanks, this looks really helpful. I don't really know enough about spark sql to offer much in the way of high-level comments, but I have a number of minor comments.

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +  ^{:doc "Coerce `org.apache.spark.sql SparkSession.Row` objects into Clojure
nit: use singular ("Coerce an `org....` object into...")

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +    (loop [i 0 m (transient {})]
Are you doing a `loop` instead of `reduce` for performance? If so, does `i` need to be type-hinted to int?

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +  (let [type (or type :parquet)
Should this default not go in the `:or` section in parameters above?

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +        options (java.util.HashMap.)
Can't you just pass a literal map as `options` instead of building a mutable thing?

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +        ((fn [df]
I think you should probably just use `cond->` here instead of just the `->`--it looks like that'd be cleaner.

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +  (-> (.getOrCreate (SparkSession/builder))
likewise use `cond->`?

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +  (-> (query url "select * from tmp" :type type)
Does hardcoding in `tmp` do the right thing here? I haven't worked with spark-sql.

2017-12-12 06:06 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +(defn ^Dataset flat-map
I think this function was duplicated.

2017-12-13 16:00 UTC, plandes commented on src/clojure/flambo/sql.clj
> +  ^{:doc "Coerce `org.apache.spark.sql SparkSession.Row` objects into Clojure
Agree

2017-12-13 16:01 UTC, plandes commented on src/clojure/flambo/sql.clj
> +    (loop [i 0 m (transient {})]
Agree

2017-12-13 16:01 UTC, plandes commented on src/clojure/flambo/sql.clj
> +  (let [type (or type :parquet)
Agree

2017-12-13 16:04 UTC, plandes commented on src/clojure/flambo/sql.clj
> +        options (java.util.HashMap.)
I could, but then the caller of the function needs to know details of what I consider some strange keys like `inferSchema`.  Also for this case it has to calculate it based on if a schema is provided *and* whether or not we explicitly ask for it with `infer-schema?`.

I'm up for suggestions though.

2017-12-13 16:29 UTC, plandes commented on src/clojure/flambo/sql.clj
> +        ((fn [df]
Agree

2017-12-13 16:34 UTC, plandes commented on src/clojure/flambo/sql.clj
> +  (-> (query url "select * from tmp" :type type)
After using `(.createOrReplaceTempView <sql-context> "table-name")` `table-name` is then used in the SQL string.  The important thing is there is symmetry between the name given`setup-temp-view` and the name used in SQL.

2017-12-13 16:35 UTC, plandes commented on src/clojure/flambo/sql.clj
> +(defn ^Dataset flat-map
Sorry and thank you.

2017-12-13 16:35 UTC, plandes commented
I have also renamed `setup-temp-view` -> `setup-temporary-view`

2017-12-13 16:44 UTC, plandes commented on src/clojure/flambo/sql.clj
> +  (let [type (or type :parquet)
I tried this:

```clojure
(loop [^Integer i 0 m (transient {})]
```

But I get this error:
```
Can't type hint a local with a primitive initializer, compiling:(flambo/sql.clj:217:3)
```

Then I tried to put it in a `let` toward [this](https://stackoverflow.com/questions/33012262/how-to-know-where-to-put-type-hints-to-improve-numeric-performance-in-clojure) solution but that didn't work either.  How do you type hint in a loop?

2017-12-13 19:35 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +    (loop [i 0 m (transient {})]
In response to your comment on `Can't type hint a local with a primitive initializer`, I guess you can't do the thing I was suggesting. Nevermind--thanks for trying.

2017-12-13 19:47 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +        options (java.util.HashMap.)
I think we can construct the map here rather than requiring the caller to do so. Could you do something like this? I think it'd be nicer than the mutable stuff.

```clojure
(let [options (merge {"path" url}
                     (if (and (= type :csv) csv-options)
                       csv-options)
                     (if (and (nil? schema) infer-schema?)
                       {"inferSchema" "true"})]
  ...)
```

2017-12-13 19:59 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +  (-> (query url "select * from tmp" :type type)
I think I see--the default in `query` is to make a table `"tmp"`, and you're using that here. I'd prefer if that were made explicit, so that you called `(query ... :table "tmp")`. I'd also prefer if you use a different table name like `"schema-tmp"` to avoid collisions with users' actual tables, but I'm not as familiar with the API so maybe that's not necessary.

2017-12-13 19:59 UTC, leon-barrett commented
Thanks for the changes.

2017-12-14 17:41 UTC, plandes commented
You're welcome.  Is there anything else I need to do?

2017-12-14 18:48 UTC, leon-barrett commented
@plandes Hmm, I guess my additional comments are kind of hidden, so let me link to them:

https://github.com/yieldbot/flambo/pull/129#discussion_r156763408
https://github.com/yieldbot/flambo/pull/129#discussion_r156766654

2017-12-15 00:01 UTC, plandes commented on src/clojure/flambo/sql.clj
> +        options (java.util.HashMap.)
Sure, that should work, but note that spark wants a Map<String,String> so we have to stringify (from keywords) the keys.

2017-12-15 00:03 UTC, plandes commented on src/clojure/flambo/sql.clj
> +  (-> (query url "select * from tmp" :type type)
There shouldn't be collisions since temporary views are per spark context, and therefore, per JVM.  However, it doesn't hurt to call it something else and a longer name will motivate us to come up with a good name :)

2017-12-15 00:04 UTC, plandes commented
I'm not sure why I didn't see 129 comments.

2017-12-15 05:11 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +        options (java.util.HashMap.)
Yes, I agree. That's why my example has strings as keys :)

2017-12-15 05:13 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +        options (java.util.HashMap.)
Ah, I see, nevermind--your implementation looks great.

2017-12-15 05:18 UTC, leon-barrett commented on src/clojure/flambo/sql.clj
> +  (-> (.getOrCreate (SparkSession/builder))
can you use a `cond->` here too?

2017-12-18 18:22 UTC, leon-barrett approved these changes

2017-12-18 18:22 UTC, leon-barrett commented
Cool, thanks!

2017-12-18 18:22 UTC, merged